apiVersion: apps/v1
kind: Deployment
metadata:
  name: item-service
  labels:
    app: item-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: item-service
  template:
    metadata:
      labels:
        app: item-service
    spec:
      containers:
        - name: item-service
          image: rosignol/item-service:0.0.3
          env:
            - name: ENV
              value: dev
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: item-service
  labels:
    app: item-service
spec:
  selector:
    app: item-service
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30001
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: item-service
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx
  rules:
    - host: arch.homework
      http:
          paths:
            - path: /api/item/.*
              pathType: ImplementationSpecific
              backend:
                service:
                  name: item-service
                  port:
                    number: 80
